/**
 * Best-effort TypeScript type generation from env schemas.
 *
 * Generated types represent the **coerced output schema** (what resolve() returns).
 * process.env augmentations remain string-ish at runtime — these are convenience,
 * not enforcement. Edge cases (custom validators, complex compositions) fall back
 * to `string`.
 *
 * @example
 * ```ts
 * import { generateTypes, writeTypes } from 'node-env-resolver/typegen';
 * import { string, number, oneOf, sensitive } from 'node-env-resolver/validators';
 *
 * const schema = {
 *   PORT: number({ default: 3000, description: 'Server port' }),
 *   API_KEY: sensitive(string({ description: 'API key for external service' })),
 *   NODE_ENV: oneOf(['development', 'production', 'test'] as const),
 * };
 *
 * const types = generateTypes(schema);
 * writeTypes(schema, './env.d.ts');
 * ```
 */

import type { SimpleEnvSchema, Validator, ValidatorMeta } from './types';
import { writeFileSync } from 'fs';

export interface TypegenOptions {
  /** Augment global process.env types (default: true) */
  augmentProcessEnv?: boolean;
  /** Augment global import.meta.env types (default: true) */
  augmentImportMetaEnv?: boolean;
  /** Custom banner comment at the top of the file */
  banner?: string;
}

const DEFAULT_BANNER =
  '// Auto-generated by node-env-resolver typegen. DO NOT EDIT.\n// Regenerate with: npx node-env-resolver typegen\n';

/**
 * Map a validator's __meta.type to a TypeScript type string.
 */
function metaTypeToTsType(meta: ValidatorMeta | undefined): string {
  if (!meta?.type) return 'string';

  switch (meta.type) {
    case 'string':
    case 'url':
    case 'email':
    case 'json':
    case 'custom':
      return 'string';
    case 'number':
    case 'port':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'string[]':
      return 'string[]';
    case 'number[]':
      return 'number[]';
    case 'oneOf': {
      const values = meta.enumValues;
      if (!values || values.length === 0) return 'string';
      return values.map((v) => JSON.stringify(String(v))).join(' | ');
    }
    default:
      return 'string';
  }
}

/**
 * Map a validator's __meta.type to a string-coerced TypeScript type
 * (for process.env / import.meta.env augmentation).
 */
function metaTypeToStringType(meta: ValidatorMeta | undefined): string {
  if (!meta?.type) return 'string';

  switch (meta.type) {
    case 'boolean':
      return "'true' | 'false'";
    case 'oneOf': {
      const values = meta.enumValues;
      if (!values || values.length === 0) return 'string';
      return values.map((v) => JSON.stringify(String(v))).join(' | ');
    }
    default:
      return 'string';
  }
}

interface SchemaEntry {
  key: string;
  tsType: string;
  stringType: string;
  isOptional: boolean;
  description?: string;
  isSensitive: boolean;
}

function analyzeSchema(schema: SimpleEnvSchema): SchemaEntry[] {
  const entries: SchemaEntry[] = [];

  for (const [key, value] of Object.entries(schema)) {
    let tsType = 'string';
    let stringType = 'string';
    let isOptional = false;
    let description: string | undefined;
    let isSensitive = false;

    if (typeof value === 'function') {
      const validator = value as Validator<unknown>;
      const meta = validator.__meta;
      tsType = metaTypeToTsType(meta);
      stringType = metaTypeToStringType(meta);
      isOptional = validator.optional === true;
      description = meta?.description;
      isSensitive = meta?.sensitive === true;
    } else if (typeof value === 'number') {
      tsType = 'number';
    } else if (typeof value === 'boolean') {
      tsType = 'boolean';
      stringType = "'true' | 'false'";
    } else if (Array.isArray(value)) {
      // Array shorthand = enum
      const values = (value as readonly (string | number)[]);
      if (values.length > 0) {
        const union = values.map((v) => JSON.stringify(String(v))).join(' | ');
        tsType = union;
        stringType = union;
      }
      isOptional = (value as { __optional?: boolean }).__optional === true;
    }
    // string defaults are just 'string'

    entries.push({ key, tsType, stringType, isOptional, description, isSensitive });
  }

  return entries;
}

function buildJsDoc(entry: SchemaEntry): string {
  const lines: string[] = [];
  if (entry.description) lines.push(entry.description);
  if (entry.isSensitive) lines.push('@sensitive');
  if (lines.length === 0) return '';

  if (lines.length === 1) return `  /** ${lines[0]} */\n`;
  return `  /**\n${lines.map((l) => `   * ${l}`).join('\n')}\n   */\n`;
}

/**
 * Generate TypeScript type definitions from a schema.
 *
 * @param schema - The env schema definition
 * @param options - Generation options
 * @returns The generated .d.ts file content as a string
 */
export function generateTypes(
  schema: SimpleEnvSchema,
  options: TypegenOptions = {},
): string {
  const {
    augmentProcessEnv = true,
    augmentImportMetaEnv = true,
    banner = DEFAULT_BANNER,
  } = options;

  const entries = analyzeSchema(schema);
  const lines: string[] = [];

  if (banner) lines.push(banner);

  // Main interface
  lines.push('export interface EnvSchema {');
  for (const entry of entries) {
    const jsdoc = buildJsDoc(entry);
    if (jsdoc) lines.push(jsdoc.trimEnd());
    const opt = entry.isOptional ? '?' : '';
    lines.push(`  ${entry.key}${opt}: ${entry.tsType};`);
  }
  lines.push('}');
  lines.push('');

  // process.env augmentation
  if (augmentProcessEnv) {
    lines.push('declare global {');
    lines.push('  namespace NodeJS {');
    lines.push('    interface ProcessEnv {');
    for (const entry of entries) {
      const opt = entry.isOptional ? '?' : '';
      lines.push(`      ${entry.key}${opt}: ${entry.stringType};`);
    }
    lines.push('    }');
    lines.push('  }');
    lines.push('}');
    lines.push('');
  }

  // import.meta.env augmentation
  if (augmentImportMetaEnv) {
    lines.push('interface ImportMetaEnv {');
    for (const entry of entries) {
      const opt = entry.isOptional ? '?' : '';
      lines.push(`  ${entry.key}${opt}: ${entry.stringType};`);
    }
    lines.push('}');
    lines.push('');
    lines.push('interface ImportMeta {');
    lines.push('  readonly env: ImportMetaEnv;');
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generate TypeScript type definitions and write them to a file.
 *
 * @param schema - The env schema definition
 * @param outputPath - Path to write the .d.ts file
 * @param options - Generation options
 */
export function writeTypes(
  schema: SimpleEnvSchema,
  outputPath: string,
  options?: TypegenOptions,
): void {
  const content = generateTypes(schema, options);
  writeFileSync(outputPath, content, 'utf8');
}
