import { describe, it, expect } from 'vitest';
import { generateTypes } from './typegen';
import { string, number, boolean, port, url, email, oneOf, sensitive, postgres, stringArray } from './validators';

describe('typegen', () => {
  it('generates types for basic validators', () => {
    const output = generateTypes({
      HOST: string({ default: 'localhost' }),
      PORT: number({ default: 3000 }),
      DEBUG: boolean({ default: false }),
    }, { augmentProcessEnv: false, augmentImportMetaEnv: false });

    expect(output).toContain('HOST: string;');
    expect(output).toContain('PORT: number;');
    expect(output).toContain('DEBUG: boolean;');
  });

  it('marks optional validators with ?', () => {
    const output = generateTypes({
      OPTIONAL_KEY: string({ optional: true }),
      REQUIRED_KEY: string(),
    }, { augmentProcessEnv: false, augmentImportMetaEnv: false });

    expect(output).toContain('OPTIONAL_KEY?: string;');
    expect(output).toContain('REQUIRED_KEY: string;');
    expect(output).not.toContain('REQUIRED_KEY?');
  });

  it('maps port to number', () => {
    const output = generateTypes({
      PORT: port({ default: 3000 }),
    }, { augmentProcessEnv: false, augmentImportMetaEnv: false });

    expect(output).toContain('PORT: number;');
  });

  it('maps url and email to string', () => {
    const output = generateTypes({
      API_URL: url(),
      ADMIN_EMAIL: email(),
    }, { augmentProcessEnv: false, augmentImportMetaEnv: false });

    expect(output).toContain('API_URL: string;');
    expect(output).toContain('ADMIN_EMAIL: string;');
  });

  it('generates union types for oneOf', () => {
    const output = generateTypes({
      NODE_ENV: oneOf(['development', 'production', 'test'] as const),
    }, { augmentProcessEnv: false, augmentImportMetaEnv: false });

    expect(output).toContain('"development" | "production" | "test"');
  });

  it('handles array shorthand as enum union', () => {
    const output = generateTypes({
      LOG_LEVEL: ['debug', 'info', 'warn', 'error'] as unknown as readonly string[],
    }, { augmentProcessEnv: false, augmentImportMetaEnv: false });

    expect(output).toContain('"debug" | "info" | "warn" | "error"');
  });

  it('handles shorthand types', () => {
    const output = generateTypes({
      PORT: 3000,
      DEBUG: false,
      NAME: 'app',
    }, { augmentProcessEnv: false, augmentImportMetaEnv: false });

    expect(output).toContain('PORT: number;');
    expect(output).toContain('DEBUG: boolean;');
    expect(output).toContain('NAME: string;');
  });

  it('includes JSDoc with description', () => {
    const output = generateTypes({
      API_KEY: string({ description: 'The API key for the service' }),
    }, { augmentProcessEnv: false, augmentImportMetaEnv: false });

    expect(output).toContain('/** The API key for the service */');
  });

  it('marks sensitive fields in JSDoc', () => {
    const output = generateTypes({
      SECRET: sensitive(string({ description: 'A secret value' })),
    }, { augmentProcessEnv: false, augmentImportMetaEnv: false });

    expect(output).toContain('A secret value');
    expect(output).toContain('@sensitive');
  });

  it('generates process.env augmentation by default', () => {
    const output = generateTypes({
      PORT: number({ default: 3000 }),
    });

    expect(output).toContain('namespace NodeJS');
    expect(output).toContain('interface ProcessEnv');
  });

  it('generates import.meta.env augmentation by default', () => {
    const output = generateTypes({
      PORT: number({ default: 3000 }),
    });

    expect(output).toContain('interface ImportMetaEnv');
    expect(output).toContain('interface ImportMeta');
  });

  it('uses string types in process.env augmentation', () => {
    const output = generateTypes({
      PORT: number({ default: 3000 }),
      DEBUG: boolean({ default: false }),
    });

    // In ProcessEnv, number becomes string and boolean becomes 'true' | 'false'
    expect(output).toMatch(/interface ProcessEnv[\s\S]*PORT: string/);
    expect(output).toMatch(/interface ProcessEnv[\s\S]*DEBUG: 'true' \| 'false'/);
  });

  it('preserves enum unions in process.env augmentation', () => {
    const output = generateTypes({
      NODE_ENV: oneOf(['development', 'production', 'test'] as const),
    });

    expect(output).toMatch(/interface ProcessEnv[\s\S]*NODE_ENV: "development" \| "production" \| "test"/);
  });

  it('includes banner comment', () => {
    const output = generateTypes({
      PORT: 3000,
    });

    expect(output).toContain('Auto-generated by node-env-resolver typegen');
    expect(output).toContain('DO NOT EDIT');
  });

  it('supports custom banner', () => {
    const output = generateTypes({
      PORT: 3000,
    }, { banner: '// Custom banner\n' });

    expect(output).toContain('// Custom banner');
  });

  it('can disable augmentations', () => {
    const output = generateTypes({
      PORT: 3000,
    }, { augmentProcessEnv: false, augmentImportMetaEnv: false });

    expect(output).not.toContain('ProcessEnv');
    expect(output).not.toContain('ImportMetaEnv');
  });

  it('handles postgres as string type', () => {
    const output = generateTypes({
      DATABASE_URL: postgres(),
    }, { augmentProcessEnv: false, augmentImportMetaEnv: false });

    expect(output).toContain('DATABASE_URL: string;');
  });

  it('handles stringArray type', () => {
    const output = generateTypes({
      ORIGINS: stringArray(),
    }, { augmentProcessEnv: false, augmentImportMetaEnv: false });

    expect(output).toContain('ORIGINS: string[];');
  });

  it('falls back to string for empty oneOf', () => {
    const output = generateTypes({
      EMPTY: oneOf([] as const),
    }, { augmentProcessEnv: false, augmentImportMetaEnv: false });

    expect(output).toContain('EMPTY: string;');
  });
});
